spring.application.name=Module_Q13_User_API_microservice

#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false

eureka.client.serviceUrl.defaultZone=http://localhost:8999/eureka/